const constants = {
    ADD_TASK: "ADD_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    TOGGLE_TASK: "TOGGLE_TASK",
    CHANGE_TASK_TEXT: "CHANGE_TASK_TEXT",
    ACTIVATE_LIST: "ACTIVATE_LIST",
    TEMPORARY_SET_LIST: "SET_LIST",
    SET_INITIAL_STATE: "SET_INITIAL_STATE"
}

export default constants